import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  view0: {
    flex: 1,
    backgroundColor: '#ffffff',
    marginHorizontal: 25,
    marginBottom: 30,
  },
  view1: {
    borderColor: '#cccccc',
    borderWidth: 1,
    width: '100%',
    height: 120,
    borderRadius: 10,
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  view2: {
    flexDirection: 'column',
    height: 60,
    width: '100%',
    justifyContent: 'center',
  },
  view3: {
    borderWidth: 0.5,
    borderStyle: 'dashed',
    width: '100%',
  },
  view4: {
    justifyContent: 'center',
  },
  view5: {
    width: 110,
    height: 30,
    backgroundColor: '#00c4ae',
    position: 'absolute',
    left: -25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  view8: {
    flexDirection: 'row',
    position: 'absolute',
  },
  view7: {
    width: 110,
    height: 30,
    backgroundColor: '#e55252',
    position: 'absolute',
    left: -25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  view6: {
    width: 110,
    height: 30,
    backgroundColor: '#4db1e9',
    position: 'absolute',
    left: -25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text0: {
    fontFamily: 'Quicksand-Bold',
    fontSize: 10,
    lineHeight: 13,
    letterSpacing: 0.65,
    textAlign: 'center',
    color: '#ffffff',
  },
  text1: {
    color: '#00c4ae',
    fontFamily: 'Quicksand-Medium',
    fontSize: 20,
    lineHeight: 25,
    textAlign: 'right',
  },
  text2: {
    fontFamily: 'Quicksand-Medium',
    fontSize: 12,
    lineHeight: 15,
    textAlign: 'left',
    color: '#000000',
  },
  text5: {
    color: '#9b9b9b',
    fontFamily: 'Quicksand-Bold',
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'right',
  },
});
