import {useFormik} from 'formik';
import {Container} from 'native-base';
import React, {useCallback} from 'react';
import {Text, TouchableOpacity} from 'react-native';
import {Button, Header, Input} from 'react-native-elements';
import LinearGradient from 'react-native-linear-gradient';
import * as yup from 'yup';
import back from '../../assets/icon/back/back.png';
import ErrorPopUp from '../error_pop_up/error_pop_up';
import Loading from '../loading/loading';
import {MTPImage0} from '../../component/mtp_image/index';
import {MyScrollView0} from '../../component/my_scroll_view/my_scroll_view';
import SuccessPopUp from '../../component/success_pop_up/success_pop_up';
import {PHONE_MAX_LENGTH, FULLNAME_MAX_LENGTH} from '../../constant/app';
import {convertToSingleSpace, noSpaceAtEntry} from '../../utility/string';
import useAddCustomer1 from '../customer_list_from_order/hook';
import useTodo from './hook';
import styles from './style';
import MyInput from '../../component/input/input';
import {PrimaryButton} from '../../component/primary_button/primary_button';
